In [5]:
import numpy as np

class SudokuBacktrackingSolver:
    def __init__(self, puzzle):
        self.grid = np.array(puzzle)

    def is_safe(self, row, col, num):
        # Check if num is not in the current row
        if num in self.grid[row, :]:
            return False
        
        # Check if num is not in the current column
        if num in self.grid[:, col]:
            return False

        # Check if num is not in the current 3x3 subgrid
        subgrid_x, subgrid_y = 3 * (row // 3), 3 * (col // 3)
        if num in self.grid[subgrid_x:subgrid_x + 3, subgrid_y:subgrid_y + 3]:
            return False

        return True

    def find_empty_location(self):
        # Find an empty cell (0 represents empty cells)
        for row in range(9):
            for col in range(9):
                if self.grid[row, col] == 0:
                    return row, col
        return None  # No empty cell left

    def solve(self):
        empty_loc = self.find_empty_location()
        if not empty_loc:
            return True  # Puzzle is solved

        row, col = empty_loc

        for num in range(1, 10):
            if self.is_safe(row, col, num):
                self.grid[row, col] = num

                if self.solve():
                    return True

                # Backtrack
                self.grid[row, col] = 0

        return False

    def get_solution(self):
        return self.grid

# Example Sudoku Puzzle (0 represents empty cells)
sample_puzzle = [
    [5, 3, 0, 0, 7, 0, 0, 0, 0],
    [6, 0, 0, 1, 9, 5, 0, 0, 0],
    [0, 9, 8, 0, 0, 0, 0, 6, 0],
    [8, 0, 0, 0, 6, 0, 0, 0, 3],
    [4, 0, 0, 8, 0, 3, 0, 0, 1],
    [7, 0, 0, 0, 2, 0, 0, 0, 6],
    [0, 6, 0, 0, 0, 0, 2, 8, 0],
    [0, 0, 0, 4, 1, 9, 0, 0, 5],
    [0, 0, 0, 0, 8, 0, 0, 7, 9]
]

solver = SudokuBacktrackingSolver(sample_puzzle)
if solver.solve():
    print("Solved Sudoku:")
    print(solver.get_solution())
else:
    print("No solution exists for the given puzzle.")


Solved Sudoku:
[[5 3 4 6 7 8 9 1 2]
 [6 7 2 1 9 5 3 4 8]
 [1 9 8 3 4 2 5 6 7]
 [8 5 9 7 6 1 4 2 3]
 [4 2 6 8 5 3 7 9 1]
 [7 1 3 9 2 4 8 5 6]
 [9 6 1 5 3 7 2 8 4]
 [2 8 7 4 1 9 6 3 5]
 [3 4 5 2 8 6 1 7 9]]
